version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=jank_db
      - POSTGRES_USER=<DATABASE_USER>
      - POSTGRES_PASSWORD=<DATABASE_PASSWORD>
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jank_blog_network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fender", "-d", "jank_db"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s

  redis:
    image: redis:7.0
    container_name: redis_db
    restart: unless-stopped
    command: redis-server --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - jank_blog_network

  app:
    build: Jank
    container_name: jank_blog_app
    restart: unless-stopped
    ports:
      - "9010:9010"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./configs:/app/configs
    networks:
      - jank_blog_network

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - jank_blog_network

volumes:
  postgres_data:
  redis_data:

networks:
  jank_blog_network:
    driver: bridge
