version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=jank_db
      - POSTGRES_USER=<DATABASE_USER>
      - POSTGRES_PASSWORD=<DATABASE_PASSWORD>
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "fender", "-d", "jank_db"]
      interval: 30s
      timeout: 10s
      retries: 30
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jank_blog_network

  redis:
    image: redis:7.0
    container_name: redis_db
    restart: unless-stopped
    command: redis-server --save ""
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - redis_data:/data
    networks:
      - jank_blog_network

  app:
    build: ./backend
    container_name: jank_blog_backend_app
    restart: unless-stopped
    ports:
      - "9010:9010"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./backend/configs:/app/configs
    networks:
      - jank_blog_network

  frontend:
    build: ./frontend
    container_name: jank_blog_frontend_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/public:/app/public
      - frontend_next_static:/app/.next/static
    networks:
      - jank_blog_network

  nginx:
    image: nginx:1.24.0
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./configs/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/ssl:ro
      - ./logs/nginx:/var/log/nginx
      - ./frontend/public:/app/public:ro
    networks:
      - jank_blog_network
    command: >
      bash -c "mkdir -p /var/cache/nginx/proxy_cache &&
              chown -R nginx:nginx /var/cache/nginx &&
              nginx -g 'daemon off;'"
    depends_on:
      - frontend
      - app

networks:
  jank_blog_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  frontend_next_static:
