# 应用相关
app:
  APP_NAME: "JANK_BLOG"
  APP_HOST: "localhost" # 如果使用docker，则改为"0.0.0.0"
  APP_PORT: "9010"
  EMAIL_TYPE: "qq" # 支持的邮箱类型: qq, gmail, outlook
  FROM_EMAIL: "<FROM_EMAIL>"
  EMAIL_SMTP: "<EMAIL_SMTP>"

database:
  DB_NAME: "jank_db"
  DB_HOST: "127.0.0.1" # 如果使用docker，则改为"postgres_db"
  DB_PORT: "5432"
  DB_USER: "<DATABASE_USER>"
  DB_PSW: "<DATABASE_PASSWORD>"

# Redis 相关
redis:
  REDIS_HOST: "127.0.0.1" # 如果使用docker，则改为"redis_db"
  REDIS_PORT: "6379"
  REDIS_DB: "0"
  REDIS_PSW: ""

# 日志相关
log:
  LOG_FILE_PATH: ".logs/"
  LOG_FILE_NAME: "app.log"
  LOG_TIMESTAMP_FMT: "2006-01-02 15:04:05"
  LOG_MAX_AGE: 72
  LOG_ROTATION_TIME: 24
  LOG_LEVEL: "INFO"

# 插件相关
plugin:
  ENABLE: true
  PLUGIN_DIR: "./plugins"
  AUTO_LOAD: true
  LOAD_TIMEOUT: 32
  INIT_TIMEOUT: 32

# Swagger 相关
swagger:
  SWAGGER_HOST: "localhost:9010"
